name: 'Deploy PR build'
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    # This job only runs for pull request comments
    name: Build and deploy to test
    if: contains(github.event.comment.body, 'deploy to test')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUILD_TOKEN }}

      - name: Push to test
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        # Only run on main branch push (e.g. after pull request merge).
        run: |
          git push origin $BRANCH_NAME:test --force-with-lease