name: 'Deploy PR build'
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    # This job only runs for pull request comments
    name: Build and deploy to test
    if: contains(github.event.comment.body, 'deploy to test')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to test
        run: |
          echo "Deploying to test for PR ${{ github.event.pull_request.number }}"
          # Add your deployment steps here