name: 'Deploy PR build'
on:
  issue_comment:
    types: [created]
  env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  deploy:
    # This job only runs for pull request comments
    name: Build and deploy to test
    if: contains(github.event.comment.body, 'deploy to test')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to test
        # Only run on main branch push (e.g. after pull request merge).
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "username@users.noreply.github.com"
          git push origin {env.BRANCH_NAME}:test --force-with-lease